# Generated by Django 4.1.1 on 2022-12-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('lote', models.IntegerField()),
                ('producto', models.CharField(max_length=50)),
                ('componente', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('kg', models.FloatField()),
                ('NI1', models.IntegerField()),
                ('NI2', models.IntegerField()),
                ('componente_2', models.CharField(blank=True, max_length=50)),
                ('codigo_2', models.IntegerField(null=True)),
                ('kg_2', models.FloatField(null=True)),
                ('NI1_2', models.IntegerField(null=True)),
                ('NI2_2', models.IntegerField(null=True)),
                ('componente_3', models.CharField(blank=True, max_length=50)),
                ('codigo_3', models.IntegerField(null=True)),
                ('kg_3', models.FloatField(null=True)),
                ('NI1_3', models.IntegerField(null=True)),
                ('NI2_3', models.IntegerField(null=True)),
                ('componente_4', models.CharField(blank=True, max_length=50)),
                ('codigo_4', models.IntegerField(null=True)),
                ('kg_4', models.FloatField(null=True)),
                ('NI1_4', models.IntegerField(null=True)),
                ('NI2_4', models.IntegerField(null=True)),
                ('componente_5', models.CharField(blank=True, max_length=50)),
                ('codigo_5', models.IntegerField(null=True)),
                ('kg_5', models.FloatField(null=True)),
                ('NI1_5', models.IntegerField(null=True)),
                ('NI2_5', models.IntegerField(null=True)),
                ('componente_6', models.CharField(blank=True, max_length=50)),
                ('codigo_6', models.IntegerField(null=True)),
                ('kg_6', models.FloatField(null=True)),
                ('NI1_6', models.IntegerField(null=True)),
                ('NI2_6', models.IntegerField(null=True)),
                ('componente_7', models.CharField(blank=True, max_length=50)),
                ('codigo_7', models.IntegerField(null=True)),
                ('kg_7', models.FloatField(null=True)),
                ('NI1_7', models.IntegerField(null=True)),
                ('NI2_7', models.IntegerField(null=True)),
                ('componente_8', models.CharField(blank=True, max_length=50)),
                ('codigo_8', models.IntegerField(null=True)),
                ('kg_8', models.FloatField(null=True)),
                ('NI1_8', models.IntegerField(null=True)),
                ('NI2_8', models.IntegerField(null=True)),
                ('componente_9', models.CharField(blank=True, max_length=50)),
                ('codigo_9', models.IntegerField(null=True)),
                ('kg_9', models.FloatField(null=True)),
                ('NI1_9', models.IntegerField(null=True)),
                ('NI2_9', models.IntegerField(null=True)),
                ('componente_10', models.CharField(blank=True, max_length=50)),
                ('codigo_10', models.IntegerField(null=True)),
                ('kg_10', models.FloatField(null=True)),
                ('NI1_10', models.IntegerField(null=True)),
                ('NI2_10', models.IntegerField(null=True)),
                ('observacion', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
