# Generated by Django 4.1.1 on 2022-12-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication', '0002_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='NI1',
            new_name='NI1_1',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='NI2',
            new_name='NI2_1',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='codigo',
            new_name='codigo_1',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='componente',
            new_name='componente_1',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='kg',
            new_name='kg_1',
        ),
    ]
