# Generated by Django 4.1.1 on 2022-12-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication', '0003_rename_ni1_producto_ni1_1_rename_ni2_producto_ni2_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='NI2_1',
            field=models.IntegerField(null=True),
        ),
    ]
