# Generated by Django 4.1.3 on 2022-12-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('ni', models.AutoField(default=1000, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.CharField(max_length=16)),
                ('fecha_vencimiento', models.CharField(max_length=10)),
                ('cantidad', models.FloatField()),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('oc', models.IntegerField()),
                ('nlote', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('existencia', models.FloatField(default=0)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
